// navigations
const PROFILE_ONBOARDING_NAVIGATION = 'PROFILE_ONBOARDING_NAVIGATION';
const HOME_NAVIGATION = 'HOME_NAVIGATION';
const TAB_NAVIGATION = 'TAB_NAVIGATION';
const AUTH_NAVIGATION = 'AUTH_NAVIGATION';

// auth
const WELCOME_SCREEN = 'WELCOME_SCREEN';
const SIGN_IN_SCREEN = 'SIGN_IN_SCREEN';

// onboarding screens
const GENDER_SCREEN = 'GENDER_SCREEN';
const BIO_DATA_SCREEN = 'BIO_DATA_SCREEN';
const PASSION_SCREEN = 'PASSION_SCREEN';
const NOTIFICATION_SCREEN = 'NOTIFICATION_SCREEN';

// navigation modals
const PROFILE_MODAL = 'PROFILE_MODAL';
const GALLERY_MODAL = 'GALLERY_MODAL';
const PHOTO_MODAL = 'PHOTO_MODAL';
const MATCH_SUCCESS = 'MATCH_SUCCESS';

// home screens
const HOME_SCREEN = 'HOME_SCREEN';
const MATCH_SCREEN = 'MATCH_SCREEN';
const CHAT_SCREEN = 'CHAT_SCREEN';
const PROFILE_SCREEN = 'PROFILE_SCREEN';
const EDIT_PROFILE_SCREEN = 'EDIT_PROFILE_SCREEN';
const WEB_SCREEN = 'WEB_SCREEN';

export default {
  PROFILE_ONBOARDING_NAVIGATION,
  AUTH_NAVIGATION,
  HOME_NAVIGATION,
  TAB_NAVIGATION,
  WELCOME_SCREEN,
  SIGN_IN_SCREEN,
  GENDER_SCREEN,
  BIO_DATA_SCREEN,
  PASSION_SCREEN,
  NOTIFICATION_SCREEN,
  HOME_SCREEN,
  MATCH_SCREEN,
  CHAT_SCREEN,
  PROFILE_SCREEN,
  PROFILE_MODAL,
  GALLERY_MODAL,
  PHOTO_MODAL,
  MATCH_SUCCESS,
  WEB_SCREEN,
  EDIT_PROFILE_SCREEN,
} as const;
