const MEET_TAG = 'MEET_TAG';
const MEET_REQUEST_TAG = 'MEET_REQUEST_TAG';
const NOTIFICATION_TAG = 'NOTIFICATION_TAG';
const PROFILE_TAG = 'PROFILE_TAG';

export default {MEET_TAG, MEET_REQUEST_TAG, NOTIFICATION_TAG, PROFILE_TAG};
